#!/bin/bash

echo "***** CREATING DATABASE *****"
psql -U postgres <<- ENDSQL
  CREATE DATABASE tr_store WITH ENCODING 'UTF8';
  CREATE USER tr_user WITH PASSWORD 'tr_user';
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO tr_user;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO tr_user;
ENDSQL
echo "***** CREATED *****"
